image : maven:latest

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

stages:
  - build
  - clean
  - package
  - test1

before_script:
  - apt-get update && apt-get install -y git

clean:
  stage: build
  script:
    - mvn clean

package:
  stage: build
  script:
    - mvn package

test1:
  stage: test1
  script:
   java -jar "target\Remboursement.jar" "Reclamation.json" "Remboursement.json"