image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean
    - mvn package
  artifacts:
    paths:
      - target/Remboursement.jar

test:
  stage: test
  script:
    - java -Xmx2g -Xms2g -jar "target/Remboursement.jar" "Assurance.json" "Resultat.json"
