stages:
  - build
  - test
  - deploy

variables:
    JAVA_TOOL_OPTIONS: "-Xss512k -XX:+UseSerialGC -Xmx512m"

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean
    - mvn package

test:
  stage: test
  image: maven:latest
  script:
    - java -jar target/Remboursement.jar Test.json Test-output.json
    - diff -u Test-output.json Test-expected-output.json

deploy:
  stage: deploy
  image: maven:latest
  script:
    - java -jar target/Remboursement.jar Reclamation.json Remboursement.json
  artifacts:
    paths:
      - Remboursement.json
