image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean
    - mvn package
  artifacts:
    paths:
      - target/Remboursement.jar

test:
  stage: test
  script:
    - java -jar "target/Remboursement.jar" "Reclamation.json" "Remboursement.json"
