image : maven:latest

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

stages:
  - build
  - test

before_script:
  - export JAVA_TOOL_OPTIONS="-XX:+UseSerialGC -Xmx512m"
  - apt-get update && apt-get install -y git
  - mvn clean

build:
  stage: build
  script:
    - mvn package

test1:
  stage: test
  script:
   java -jar "target\Remboursement.jar" "Reclamation.json" "Remboursement.json"