image: maven:latest

stages:
  - build

java-build:
  # select the most appropriate image for your project
  stage: build
  script:
    - mvn package -DskipTests=true

java-run :
  stage: build
  script: 
    java -jar "target\Remboursement.jar" "Reclamation.json" "Remboursement.json"